language: php
matrix:
  include:
  - name: "php 5.6 + sf 2"
    php: "5.6"
    env: [SYMFONY_VERSION="^2.0"]
  - name: "php 7.1 + sf 2"
    php: "7.1"
    env: [SYMFONY_VERSION="^2.0"]

  - name: "php 5.6 + sf 3"
    php: "5.6"
    env: [SYMFONY_VERSION="^3.0"]
  - name: "php 7.1 + sf 3"
    php: "7.1"
    env: [SYMFONY_VERSION="^3.0"]

  - name: "php 7.1 + sf 4"
    php: "7.1"
    env: [SYMFONY_VERSION="^4.0"]

cache: bundler

install:
  - composer require symfony/symfony:${SYMFONY_VERSION}
  - composer require phpunit/phpunit php-coveralls/php-coveralls phpunit/phpcov

  - composer install


after_success:
  - travis_retry php vendor/bin/php-coveralls
